name: Release
on:
  push:
    tags: ['v*']

permissions:
  contents: write
  id-token: write
  packages: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Guard tag matches package.json version
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          PKG="$(node -p "require('./package.json').version")"
          echo "tag=$TAG pkg=$PKG"
          test "$TAG" = "$PKG"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: pnpm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     generate_release_notes: true
